CREATE TABLE EMPLOYEE (
    EMPLOYEE_UUID STRING(36) NOT NULL,
    USER_NAME STRING(20) NOT NULL,
    PASSWORD STRING(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (EMPLOYEE_UUID, USER_NAME),
ROW DELETION POLICY (OLDER_THAN(CREATED_AT, INTERVAL 1 DAY));
